services:
  db:
    container_name: 'productsMS'
    image: postgres:16.3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=administrador
      - POSTGRES_DATABASE=productsMS
      - POSTGRES_PASSWORD=admin123
    restart: always
    ports:
      - '5432:5432'

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.6
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@salamanx.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    restart: always
